version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ./.docker-env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    depends_on:
      - postgres
    restart: always
    image: golang:buster
    command: /api/scripts/wait-for-it/wait-for-it.sh postgres:5432 -t 120 -- /api/scripts/setup-postgres/setup-postgres-and-run-api.sh
    env_file:
      - ./.docker-env
    environment:
      - TEST=true
      - ENVIRONMENT=development
    volumes:
      - .:/api
    ports:
      - 7000:7000
    extra_hosts:
      - host.docker.internal:host-gateway

  e2etests:
    depends_on:
      - api
    image: node:14-stretch
    command: /api/scripts/wait-for-it/wait-for-it.sh api:7000 -t 300 -- make -C /api e2etest-compose
    environment:
      API_HOST: "http://api:7000/"
    volumes:
      - .:/api
