version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.docker-env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  start-postgres:
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
    #replace this with an image that contains dependencies required by setup-postgres.sh
    image: golang:buster
    command: /api/scripts/wait-for-it/wait-for-it.sh postgres:5432 -t 120 -- /api/scripts/setup-postgres/setup-postgres.sh
    env_file:
      - ./.docker-env
    volumes:
      - .:/api

  api:
    depends_on:
      - start-postgres
    image: golang:buster
    command: ["/bin/bash", "-c", "cd /api/ && make run"]
    env_file:
      - ./.docker-env
      - ./.api-env
      - ./.opencollective-env
    volumes:
      - .:/api
    ports:
      - 7000:7000
